[workspace]
authors = ["Juliane Hoffmann <juliane.hoffmann@fau.de>"]
channels = ["conda-forge"]
name = "SpliceAwareGRN"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.8.*"
pip = ">=25.1.1,<26"
ipykernel = ">=6.29.5,<7"
plotly = ">=6.1.2,<7"

[pypi-dependencies]
lda = "==3.0.0"
numpy = "==1.26.4"
scipy = "==1.12.0"
pandas = "==1.5.0"
scanpy = "==1.8.2"
matplotlib = "==3.6.3"
arboreto = "==0.1.6"
networkx = "==3.2.1"
igraph = "==0.11.8"
gseapy = ">=1.1.9, <2"

